export const GET_ERRORS = "GET_ERRORS";
export const USER_LOADING = "USER_LOADING";
export const SET_CURRENT_USER = "SET_CURRENT_USER";

export const GET_VOLUNTEERS = "GET_VOLUNTEERS";
export const GET_VOLUNTEERS_DEP = "GET_VOLUNTEERS_DEP";
export const GET_VOLUNTEER_BY_ID = "GET_VOLUNTEER_BY_ID";

export const GET_PROJECTS = "GET_PROJECTS";
export const GET_PROJECT_ID = "ID";
export const GET_PROJECT_TASKS = "GET_PROJECT_TASKS";
export const GET_PROJECT_TASK_ID = "GET_PROJECT_TASK_ID";

export const GET_DEPARTMENTS = "GET_DEPARTMENTS";
